/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PPresentationIdRouteImport } from './routes/p/$presentationId'
import { Route as ApiLiveblocksAuthRouteImport } from './routes/api/liveblocks-auth'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PPresentationIdRoute = PPresentationIdRouteImport.update({
  id: '/p/$presentationId',
  path: '/p/$presentationId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLiveblocksAuthRoute = ApiLiveblocksAuthRouteImport.update({
  id: '/api/liveblocks-auth',
  path: '/api/liveblocks-auth',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/p/$presentationId': typeof PPresentationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/p/$presentationId': typeof PPresentationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/liveblocks-auth': typeof ApiLiveblocksAuthRoute
  '/p/$presentationId': typeof PPresentationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/api/liveblocks-auth' | '/p/$presentationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/api/liveblocks-auth' | '/p/$presentationId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/liveblocks-auth'
    | '/p/$presentationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiLiveblocksAuthRoute: typeof ApiLiveblocksAuthRoute
  PPresentationIdRoute: typeof PPresentationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$presentationId': {
      id: '/p/$presentationId'
      path: '/p/$presentationId'
      fullPath: '/p/$presentationId'
      preLoaderRoute: typeof PPresentationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/liveblocks-auth': {
      id: '/api/liveblocks-auth'
      path: '/api/liveblocks-auth'
      fullPath: '/api/liveblocks-auth'
      preLoaderRoute: typeof ApiLiveblocksAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiLiveblocksAuthRoute: ApiLiveblocksAuthRoute,
  PPresentationIdRoute: PPresentationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
